name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:        
        python-version: '3.7'
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install awscli
    - name: Setup AWS
      run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/e4l7l3b1/maxiplux
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
    - name: Docker Login
      run: docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}      


    - name: Docker Build Local
      run: docker build -t public.ecr.aws/e4l7l3b1/maxiplux .
    - name: Tagging 
      run: docker tag public.ecr.aws/e4l7l3b1/maxiplux:latest

    - name: Docker Push AWS ECR
      run: docker push public.ecr.aws/e4l7l3b1/maxiplux:latest
    - name: change permisions to deploy.sh
      run: chmod +x deploy.sh
    - name: Deploy App Runner
      run: sh deploy.sh
      
