name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:        
        python-version: '3.7'
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install awscli
    - name: Setup AWS
      run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.CONTAINER_REGISTRY_ID }}.dkr.ecr.us-east-1.amazonaws.com
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
   


    - name: Docker Build Local
      run: docker build -t ${{ secrets.CONTAINER_IMAGE_NAME }} .
    - name: Tagging 
      run: docker tag ${{ secrets.CONTAINER_IMAGE_NAME }}:latest ${{ secrets.CONTAINER_REGISTRY_ID }}.dkr.ecr.us-east-1.amazonaws.com/${{ secrets.CONTAINER_IMAGE_NAME }}:latest


    - name: Docker Push AWS ECR
      run: docker push ${{ secrets.CONTAINER_REGISTRY_ID }}.dkr.ecr.us-east-1.amazonaws.com/${{ secrets.CONTAINER_IMAGE_NAME }}:latest
